services:
  web:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: apache_server
    ports:
      - 8080:80
    volumes:
      - ./vistas:/var/www/html
    networks:
      - red1
    depends_on:
      - db

  
  db:
    image: mysql
    container_name: mysql_server
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=clave
    volumes:
      - ./datos/:/var/lib/mysql
      - ./script/:/docker-entrypoint-initdb.d/
    networks:
      - red1

volumes:
  datos:

networks:
  red1: